; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-tab5
src_dir = .
boards_dir = boards

[env:m5stack-tab5]
; pioarduino 是支持 arduino-esp32 3.x + ESP32-P4 的社区维护平台
; 官方 platformio/espressif32 全系列只有 2.x，不含 ESP32-P4 构建脚本
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = m5stack-tab5-p4
framework = arduino
lib_deps =
	m5stack/M5GFX    @ ^0.2.8
	m5stack/M5Unified @ ^0.2.14
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
monitor_speed = 115200
upload_speed = 1500000
monitor_filters = esp32_exception_decoder
upload_speed = 921600
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM
